name: luckin_coffee_demo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  dio: ^3.0.9
  path: ^1.7.0
  fluro: ^1.7.7
  logger: ^0.9.2
  crypto: ^2.1.5
  rxdart: ^0.24.1
  equatable: ^1.2.3
  sqflite: ^1.3.1+1
  connectivity: ^2.0.2
  package_info: ^0.4.3
  flutter_bloc: ^6.0.1
  fluttertoast: ^7.0.4
  flutter_swiper: ^1.1.6
  path_provider: ^1.6.14
  shared_preferences: ^0.5.8
  loading_indicator_view: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter:
 
  uses-material-design: true
  assets:
     - lib/assets/images/
     - lib/assets/images/banners/
     - lib/assets/images/home/
     - lib/assets/images/menu/
     - lib/assets/images/navigatioinBar/
     - lib/assets/images/order/
     - lib/assets/images/shopping/
     - lib/assets/images/persion/
     - lib/assets/images/wallet/
     - lib/assets/images/login/
     - lib/assets/images/specification/
 